# fly.toml app configuration file generated for crowdcounting-l4w5mw on 2026-01-05T19:13:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "crowdcounting-l4w5mw"
primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8080"
PYTHONUNBUFFERED = "1"

[experimental.attached]
secrets = { }

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

  [[http_service.checks]]
  grace_period = "5m0s"
  interval = "30s"
  method = "GET"
  path = "/health"
  timeout = "30s"

  [http_service.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[[vm]]
cpu_kind = "performance"
cpus = 1
memory = "4gb"
memory_mb = 1_024
